PROJECT/pizza/orders/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^$', views.menu, name='menu'),
    url(r'^(?P<pizza_id>[0-9]+)/$', views.menu_item_size, name='menu_item_size'),
    url(r'^(?P<pizza_id>[0-9]+)/(?P<size_id>[0-9]+)/$', views.menu_item, name='menu_item'),
    url(r'^(?P<pizza_id>[0-9]+)/(?P<size_id>[0-9]+)/push_on_cart/$', views.push_on_cart, name='push_on_cart'),
    url(r'^cart/show$', views.show_cart, name='show_cart'),
    url(r'^cart/clear$', views.clear_cart, name='clear_cart'),
    url(r'^order/confirm$', views.confirm_order, name='confirm_order'),
    url(r'^order/place$', views.place_order, name='place_order'),
    url(r'^order/thanks$', views.thanks, name='thanks'),
    url(r'^staff/open_orders$', views.ShowOpenOrders.as_view(), name='show_open_orders'),
    url(r'^staff/set_order_state/(?P<order_id>[0-9]+)/(?P<state>[0-9]+)/$', views.set_order_state, name='set_order_state')
]

PROJECT/pizza/pizza/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('orders.urls')),
    url(r'^admin/', admin.site.urls),
]

PROJECT/pizza/orders/models.py
import datetime

from django.db import models
from django.utils import timezone

"""
We need the following objects:

    Pizzas - A pizza has a name and a price. (TODO: Maybe at description and image?)
             The Model "MenuPizza" acts as both the source for the menu view and
             as a template for "OrderPizza", which can be placed inside an order with
             additional toppings.

    Size - Size of the pizza

    Topping - A Topping can be ordered to be placed on a pizza.
              

    Cart - The customers cart. Contains "OrderPizzas"

    Order - Created from a non-empty cart. Contains a number of OrderPizzas and the customers
            name and address.

"""

class MenuPizza(models.Model):
    name = models.CharField(max_length=80)
    price = models.IntegerField(default=0) # in cents

    def __str__(self):
        return self.name

    def readable_price(self):
        """ Returns the price in euros, with 2 cent-digits after the decimal-point """
        price_str = str(self.price / 100.0)
        # find the '.' and add a second 0, if necessary
        for i in range(len(price_str)):
            if price_str[i] != '.':
                continue
            if i >= len(price_str) - 2:
                price_str += "0"
                break
        return price_str

class MenuSize(models.Model):
    name = models.CharField(max_length=10)
    price = models.IntegerField(default=0) # in cents
    ntopings = models.IntegerField(default=3) # number of available toppings
    allows_splitting = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def readable_price(self):
        """ Returns the price in euros, with 2 cent-digits after the decimal-point """
        price_str = str(self.price / 100.0)
        # find the '.' and add a second 0, if necessary
        for i in range(len(price_str)):
            if price_str[i] != '.':
                continue
            if i >= len(price_str) - 2:
                price_str += "0"
                break
        return price_str  

    def max_toppings(self):
        return str(self.ntopings)      

class MenuTopping(models.Model):
    name = models.CharField(max_length=80)
    price = models.IntegerField(default=0) # in cents

    def __str__(self):
        return self.name

    def readable_price(self):
        price_str = str(self.price / 100.0)
        # find the '.' and add a second 0, if necessary
        for i in range(len(price_str)):
            if price_str[i] != '.':
                continue
            if i >= len(price_str) - 2:
                price_str += "0"
                break
        return price_str


class Cart(models.Model):
    """
    A temporary customers cart.
    We don't need any data besides the automatically generated ID
    """
    def is_empty(self):
        return len(self.orderpizza_set.all()) == 0

    def __str__(self):
        s = "cart " + str(self.id)
        s += ":\n"
        for pizza in self.orderpizza_set.all():
            s += pizza.name() + "\n"
            s += pizza.ordersize_set.get().name()+"\n"
            for topping in pizza.ordertopping_set.all():
                s += "  " + topping.name() + "\n"
        return s

    def total(self):
        total = 0
        for pizza in self.orderpizza_set.all():
            total += pizza.price()
            total += pizza.ordersize_set.get().price()
            for topping in pizza.ordertopping_set.all():
                total += topping.price()
        return total

    def total_readable(self):
        price_str = str(self.total() / 100.0)
        # find the '.' and add a second 0, if necessary
        for i in range(len(price_str)):
            if price_str[i] != '.':
                continue
            if i >= len(price_str) - 2:
                price_str += "0"
                break
        return price_str

class OrderPizza(models.Model):
    """A pizza contained in an order."""
    pizza = models.ForeignKey(MenuPizza, on_delete=models.CASCADE, related_name='pizza')
    pizza_half = models.ForeignKey(MenuPizza, on_delete=models.CASCADE, related_name='pizza_half', null=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)

    def price(self):
        half_price = 0
        if self.pizza_half:
            half_price = self.pizza_half.price
        return self.pizza.price if self.pizza.price > half_price else self.pizza_half.price

    def readable_price(self):
        """The price in the usual e.cc format"""
        half_price = 0
        if self.pizza_half:
            half_price = self.pizza_half.price
        return self.pizza.readable_price() if self.pizza.price > half_price else self.pizza_half.readable_price()

    def name(self):
        return self.pizza.name if self.pizza_half == None else self.pizza.name + "/" + self.pizza_half.name


    def __str__(self):
        return self.name()

class OrderSize(models.Model):
    """A Size contained in an order. Belongs to a concrete OrderPizza"""
    size = models.ForeignKey(MenuSize, on_delete=models.CASCADE)
    pizza = models.ForeignKey(OrderPizza, on_delete=models.CASCADE)

    def price(self):
        return self.size.price

    def readable_price(self):
        """The price in the usual e.cc format"""
        return self.size.readable_price()

    def name(self):
        return self.size.name

    def __str__(self):
        return self.name()

class OrderTopping(models.Model):
    """A Topping contained in an order. Belongs to a concrete OrderPizza"""
    topping = models.ForeignKey(MenuTopping, on_delete=models.CASCADE)
    pizza = models.ForeignKey(OrderPizza, on_delete=models.CASCADE)

    def price(self):
        return self.topping.price

    def readable_price(self):
        """The price in the usual e.cc format"""
        return self.topping.readable_price()

    def name(self):
        return self.topping.name

    def __str__(self):
        return self.name()

class Order(models.Model):
    """A order entered into the system"""
    STATE_NEW = 0
    STATE_BAKING = 1
    STATE_DONE = 2
    
    state = models.SmallIntegerField(default=STATE_NEW)
    from_cart = models.OneToOneField(Cart, on_delete=models.CASCADE, primary_key=False)
    # Since we dont do customer registration,
    # simpy putting the name and address in the Order
    # is probably fine
    customer_name = models.CharField(max_length=255)
    customer_address = models.CharField(max_length=255)
    
    def __str__(self):
        state_str = ""
        if self.state == Order.STATE_NEW:
            state_str = "[NEW]"
        elif self.state == Order.STATE_BAKING:
            state_str = "[BAKING]"
        else:
            state_str = "[DONE]"
        return state_str + " %d" % self.from_cart.id

    def pizzas(self):
        return self.from_cart.orderpizza_set.all()
   
    def total(self):
        return self.from_cart.total_readable()

PROJECT/pizza/orders/views.py
#from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.utils import timezone

from .models import MenuPizza, MenuTopping, Cart, OrderPizza, OrderTopping, Order, MenuSize, OrderSize
from .util import *

# Helper functions for managing the cart




def menu(request):
    """Display the list of offered pizzas"""
    pizzas = MenuPizza.objects.all()
    customer_cart = None
    if is_cart_open(request):
        customer_cart = open_or_create_cart(request)
    context = { 'available_pizzas': pizzas, 'cart': customer_cart }
    return render(request, 'orders/menu.html', context)

        
def menu_item_size(request, pizza_id): 
    pizza = get_object_or_404(MenuPizza, pk=pizza_id)
    available_sizes = MenuSize.objects.all()
    return render(request, 'orders/menu_item_size.html', {'pizza': pizza, 'available_sizes': available_sizes})
  

def menu_item(request, pizza_id, size_id): 
    pizza = get_object_or_404(MenuPizza, pk=pizza_id)
    size  = get_object_or_404(MenuSize, pk=size_id)
    available_pizzas = MenuPizza.objects.all()
    available_toppings = MenuTopping.objects.all()
    return render(request, 'orders/menu_item.html',
            {'pizza': pizza, 'size': size,
                'available_toppings': available_toppings, 'available_pizzas': available_pizzas})

def push_on_cart(request, pizza_id, size_id):
    collected_toppings = False
    toppings = []
    i = 1
    while not collected_toppings:
        key = "topping" + str(i)
        if key in request.POST:
            print(key + " is in toppings")
            toppings.append(request.POST["topping" + str(i)])
            i += 1
        else:
            print(key + " is not in toppings")
            collected_toppings = True
    half_pizza_id = None
    if 'half_pizza' in request.POST:
        half_pizza_id = int(request.POST['half_pizza'])

    # Check if we have an open cart or create a new one
    customer_cart = open_or_create_cart(request)

    # Push the selected pizza and toppings onto the cart
    push_pizza_on_cart(customer_cart, pizza_id, half_pizza_id, size_id, toppings)

    return HttpResponseRedirect('/cart/show')

def show_cart(request): 
    customer_cart = open_or_create_cart(request)
    if customer_cart.is_empty():
        context = { 'is_empty': True, 'pizzas': None }
        return render(request, 'orders/show_cart.html', context)
    else:
        pizzas = OrderPizza.objects.filter(cart__id=customer_cart.id)
        context = { 'is_empty': False, 'pizzas': pizzas }
        return render(request, 'orders/show_cart.html', context)

def clear_cart(request):
    if is_cart_open(request):
       del request.session['cart_id']
    return HttpResponseRedirect('/')

def confirm_order(request):
    """Show a form asking for the clients name and address"""
    cart = None
    if is_cart_open(request):
        cart = open_or_create_cart(request)
    else:
        return HttpResponseRedirect('/') # Prevent empty orders
    return render(request, 'orders/confirm_order.html', {'cart': cart, 'total': cart.total_readable()})

def place_order(request):
    if not is_cart_open(request):
        return HttpResponseRedirect('/') # Prevent empty orders
    cart = open_or_create_cart(request)
    new_order = create_order_from_cart(cart, request.POST['name'], request.POST['addr']) 
    print("Created order " + str(new_order))
    return HttpResponseRedirect('/order/thanks')

def thanks(request):
    return render(request, 'orders/thanks.html', {})


class ShowOpenOrders(generic.ListView):
    template_name = 'orders/show_open_orders.html'
    context_object_name = 'open_orders'

    def get_queryset(self):
        """Return all unfinished orders"""
        print(Order.objects.all())
        return Order.objects.exclude(state=Order.STATE_DONE)

def set_order_state(request, order_id, state):
    order = get_object_or_404(Order, pk=order_id)
    order.state = state
    order.save()
    return HttpResponseRedirect('/staff/open_orders')

PROJECT/pizza/orders/templates/orders/confirm_order.html
<h1>Confirm your order</h1>

<h3>Pizzas:</h3>
    <ul>
        {% for pizza in cart.orderpizza_set.all %}
        <li>
            {{ pizza.name }} - {{ pizza.readable_price }} € <br />
            <span style="font-style: italic">Pizza Size </span>:
            {{ pizza.ordersize_set.get.name }} - {{ pizza.ordersize_set.get.readable_price }} € </li>
            {% if pizza.ordertopping_set.all %}
                <span style="font-style: italic">Extra toppings</span>: 
                <ul>
                    {% for topping in pizza.ordertopping_set.all %}
                    <li>{{ topping.name }} - {{ topping.readable_price }} € </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </li> 
        {% endfor %}
    </ul>
    <p>Total: {{ total }} €</p>


<form action="{% url 'orders:place_order' %}" method="post">
    {% csrf_token %}
    <input type="text" name="name" id="name" value="Your name" /> <br />
    <input type="text" name="addr" id="addr" value="Your Address" /> <br />

    <input type="submit" value="Confirm" />
</form>

Or <a href="{% url 'orders:menu' %}">Go back</a>

PROJECT/pizza/orders/templates/orders/menu.html
{% if cart %}
<p><a href="{% url 'orders:show_cart' %}">My cart</a></p>
{% endif %}

{% if available_pizzas %}
    <!-- The menu -->
    <ul>
        {% for pizza in available_pizzas %}
        <li><a href="{% url 'orders:menu_item_size' pizza.id %}">{{ pizza.name }}</a> {{ pizza.readable_price }} € </li>
        {% endfor %}
    </ul>
{% else %}
    <p>Sorry, our menu is currently empty :-( </p>
{% endif %}

PROJECT/pizza/orders/templates/orders/menu_item.html
<p>
<h1>{{ pizza.name }} - {{ size.name }}</h1>

<span style="font-style: italic">Price: {{ pizza.readable_price }} + {{ size.readable_price }} €</span>
</p>


<form action="{% url 'orders:push_on_cart' pizza.id size.id %}" method="post">
    {% csrf_token %}
    {% if available_toppings %}
    {% if size.allows_splitting %}
    Do you want to split the pizza in half? <br />
        {% for half_pizza in available_pizzas %}
        <input type="radio" name="half_pizza" id="pizza{{ forloop.counter }}" value="{{ half_pizza.id }}" />
        <label for="pizza{{ forloop.counter }}">{{ half_pizza.name }} </label> <br />
        {% endfor %}
    {% endif %}
    Do you want to select additional toppings?  <br />
    (You may select {{ size.max_toppings }} ) <br /><br />
        {% for topping in available_toppings %}
        <input type="checkbox" onclick="countCheckedBoxes(event)" name="topping{{ forloop.counter }}" id="topping{{ forloop.counter }}" value="{{ topping.id }}" />
            <label for="topping{{ forloop.counter }}">{{ topping.name }} - {{ topping.readable_price }} € </label></br />
        {% endfor %}
    {% else %}
        Sorry, we don't have any additional toppings.
    {% endif %}
    <input type="submit" value="Place on cart" />
</form>

<script>
    var checkboxes = [];
    var box = [];
    const maxAllowed = {{ size.max_toppings }};

    var getCheckboxes = function() {
        var inputs = document.getElementsByTagName('input');
        for (var i=0; i < inputs.length; i++) {
            if (inputs[i].getAttribute('type') == 'checkbox') {
                checkboxes.push(inputs[i]);
            }
        }
    };
    var countCheckedBoxes = function(e) {
        var myChosenElement = e.target || e.srcElement;
        if (myChosenElement.checked == false) {
            var pos = box.indexOf(myChosenElement);
            box.splice(pos, 1);
            disable();
        }
        if (box.length < maxAllowed) {
            if (myChosenElement.checked == true) {
                box.push(myChosenElement);
            }
            if (box.length == maxAllowed) {
                disable();
            }
        }
    };
    var disable = function() {
        if (box.length == maxAllowed) {
            for (var i = 0; i < checkboxes.length; i++) {
                checkboxes[i].disabled = true;
            }
            for (var i = 0; i < box.length; i++) {
                var pos = checkboxes.indexOf(box[i]);
                checkboxes[pos].disabled = false;
//                console.log('Enabled: '); //My debug stuff
//                console.log(checkboxes[pos]); //My debug stuff
            }
        } else {
            for (var i = 0; i < checkboxes.length; i++) {
                checkboxes[i].disabled = false;
            }
        }
//        console.log('--------- NEW TRY ---------'); //My debug stuff

    };
    window.onload = function() {
        getCheckboxes();
    };
</script>

PROJECT/pizza/orders/templates/orders/menu_item_size.html
<p>
<h1>{{ pizza.name }}</h1>

<span style="font-style: italic">Price: {{ pizza.readable_price }} €</span>
</p>
Size:</p>
{% if available_sizes %}
    <ul>
        {% for size in available_sizes %}
        <li><a href="{% url 'orders:menu_item' pizza.id size.id %}">{{ size.name }}</a> +{{ size.readable_price }} € </li>
        {% endfor %}
    </ul>
{% else %}
    Sorry, we currently don't have any sizes.
{% endif %}

PROJECT/pizza/orders/templates/orders/show_cart.html
{% if is_empty %}
<p>
    <h2>Your cart is empty</h2>
    <a href="{% url 'orders:menu' %}">Back</a>
</p>
{% else %}
<p>
    <h2>Your cart</h2>
    <h3>Pizzas:</h3>
    <ul>
        {% for pizza in pizzas %}
        <li>
            {{ pizza.name }} - {{ pizza.readable_price }} € <br />
            <span style="font-style: italic">Pizza Size </span>:
            {{ pizza.ordersize_set.get.name }} - {{ pizza.ordersize_set.get.readable_price }} € </li>
            {% if pizza.ordertopping_set.all %}
                <span style="font-style: italic">Extra toppings</span>: 
                <ul>
                    {% for topping in pizza.ordertopping_set.all %}
                    <li>{{ topping.name }} - {{ topping.readable_price }} € </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </li> 
        {% endfor %}
    </ul>

    <a href="{% url 'orders:menu' %}">Continue shopping</a> <br />
    <a href="{% url 'orders:clear_cart' %}">Clear your cart</a> <br />

    <a href="{% url 'orders:confirm_order' %}">Order</a>
</p>
{% endif %}

PROJECT/pizza/orders/templates/orders/show_open_orders.html
{% if open_orders %}
<p>
    <ul>
    {% for order in open_orders %}
    <li>
        {{ order }} <br />
        Name: {{ order.customer_name }} <br />
        Address: {{ order.customer_address }} <br />
        Total: {{ order.total }} €
        <ul>
        {% for pizza in order.pizzas %}
            <li>
                {{ pizza.name }} ({{ pizza.ordersize_set.get.name }})
                <ul>
                {% for topping in pizza.ordertopping_set.all %}
                <li>{{ topping.name }}</li>
                {% endfor %}
                </ul>
            </li>
        {% endfor %}
        </ul>
        <a href="{% url 'orders:set_order_state' order.id 0 %}">Set New</a> <br />
        <a href="{% url 'orders:set_order_state' order.id 1 %}">Set Baking</a> <br />
        <a href="{% url 'orders:set_order_state' order.id 2 %}">Set Done</a> 
    </li>
    {% endfor %}
    </ul>
</p>
{% else %}
<p>No open orders</p>
{% endif %}

PROJECT/pizza/orders/templates/orders/thanks.html
<h1>Thank you for your order<h1>
<a href="{% url 'orders:clear_cart' %}">Back to menu</a>

<script>
setTimeout(function() { window.location.replace('{% url 'orders:clear_cart' %}') }, 5000)
</script>